### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by kikinocka** [cancerit/telomerecat#16]
Hello,
I used telomerecat bam2length command, I dedicated 20 CPUs and 20 GB of memory. I prepared bam file using Bowtie2 and samtools, and I used it in a different analysis without any issue. So I don't expect a problem with the bam file itself. However, telomerecat ended with this error (several times):

```
 Generating TELBAM from: lpyr_bw2_sorted.bam
	- TELBAM generation started 2020-08-21 15:16:20
Process ChaserTask-2:
Traceback (most recent call last):
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.7.7-intel-mgiwa7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "parabam/chaser.pyx", line 701, in parabam.chaser.ChaserTask.run
  File "parabam/chaser.pyx", line 801, in __read_generator__
  File "parabam/chaser.pyx", line 820, in parabam.chaser.PrimaryHandler.__get_loner_type__
  File "parabam/chaser.pyx", line 813, in parabam.chaser.PrimaryHandler.__get_reference_id_name__
  File "parabam/chaser.pyx", line 810, in parabam.chaser.PrimaryHandler.__get_reference_id_name__.lambda3
KeyError: 0
Process ChaserTask-3:
Traceback (most recent call last):
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.7.7-intel-mgiwa7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "parabam/chaser.pyx", line 701, in parabam.chaser.ChaserTask.run
  File "parabam/chaser.pyx", line 801, in __read_generator__
  File "parabam/chaser.pyx", line 820, in parabam.chaser.PrimaryHandler.__get_loner_type__
  File "parabam/chaser.pyx", line 813, in parabam.chaser.PrimaryHandler.__get_reference_id_name__
  File "parabam/chaser.pyx", line 810, in parabam.chaser.PrimaryHandler.__get_reference_id_name__.lambda3
KeyError: 0
Process ChaserTask-4:
Traceback (most recent call last):
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.7.7-intel-mgiwa7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "parabam/chaser.pyx", line 701, in parabam.chaser.ChaserTask.run
  File "parabam/chaser.pyx", line 801, in __read_generator__
  File "parabam/chaser.pyx", line 820, in parabam.chaser.PrimaryHandler.__get_loner_type__
  File "parabam/chaser.pyx", line 813, in parabam.chaser.PrimaryHandler.__get_reference_id_name__
  File "parabam/chaser.pyx", line 810, in parabam.chaser.PrimaryHandler.__get_reference_id_name__.lambda3
KeyError: 0
Process ChaserTask-7:
Traceback (most recent call last):
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.7.7-intel-mgiwa7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "parabam/chaser.pyx", line 701, in parabam.chaser.ChaserTask.run
  File "parabam/chaser.pyx", line 801, in __read_generator__
  File "parabam/chaser.pyx", line 820, in parabam.chaser.PrimaryHandler.__get_loner_type__
  File "parabam/chaser.pyx", line 813, in parabam.chaser.PrimaryHandler.__get_reference_id_name__
  File "parabam/chaser.pyx", line 810, in parabam.chaser.PrimaryHandler.__get_reference_id_name__.lambda3
KeyError: 1
Process ChaserTask-8:
Traceback (most recent call last):
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.7.7-intel-mgiwa7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "parabam/chaser.pyx", line 701, in parabam.chaser.ChaserTask.run
  File "parabam/chaser.pyx", line 801, in __read_generator__
  File "parabam/chaser.pyx", line 820, in parabam.chaser.PrimaryHandler.__get_loner_type__
  File "parabam/chaser.pyx", line 813, in parabam.chaser.PrimaryHandler.__get_reference_id_name__
  File "parabam/chaser.pyx", line 810, in parabam.chaser.PrimaryHandler.__get_reference_id_name__.lambda3
KeyError: 2
Process ChaserTask-5:
Traceback (most recent call last):
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.7.7-intel-mgiwa7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "parabam/chaser.pyx", line 701, in parabam.chaser.ChaserTask.run
  File "parabam/chaser.pyx", line 801, in __read_generator__
  File "parabam/chaser.pyx", line 820, in parabam.chaser.PrimaryHandler.__get_loner_type__
  File "parabam/chaser.pyx", line 813, in parabam.chaser.PrimaryHandler.__get_reference_id_name__
  File "parabam/chaser.pyx", line 810, in parabam.chaser.PrimaryHandler.__get_reference_id_name__.lambda3
KeyError: 0
Process ChaserTask-10:
Traceback (most recent call last):
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.7.7-intel-mgiwa7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "parabam/chaser.pyx", line 701, in parabam.chaser.ChaserTask.run
  File "parabam/chaser.pyx", line 801, in __read_generator__
  File "parabam/chaser.pyx", line 820, in parabam.chaser.PrimaryHandler.__get_loner_type__
  File "parabam/chaser.pyx", line 813, in parabam.chaser.PrimaryHandler.__get_reference_id_name__
  File "parabam/chaser.pyx", line 810, in parabam.chaser.PrimaryHandler.__get_reference_id_name__.lambda3
KeyError: 3
Process ChaserTask-11:
Traceback (most recent call last):
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.7.7-intel-mgiwa7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "parabam/chaser.pyx", line 701, in parabam.chaser.ChaserTask.run
  File "parabam/chaser.pyx", line 801, in __read_generator__
  File "parabam/chaser.pyx", line 820, in parabam.chaser.PrimaryHandler.__get_loner_type__
  File "parabam/chaser.pyx", line 813, in parabam.chaser.PrimaryHandler.__get_reference_id_name__
  File "parabam/chaser.pyx", line 810, in parabam.chaser.PrimaryHandler.__get_reference_id_name__.lambda3
KeyError: 5
Process ChaserTask-6:
Traceback (most recent call last):
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.7.7-intel-mgiwa7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "parabam/chaser.pyx", line 701, in parabam.chaser.ChaserTask.run
  File "parabam/chaser.pyx", line 801, in __read_generator__
  File "parabam/chaser.pyx", line 820, in parabam.chaser.PrimaryHandler.__get_loner_type__
  File "parabam/chaser.pyx", line 813, in parabam.chaser.PrimaryHandler.__get_reference_id_name__
  File "parabam/chaser.pyx", line 810, in parabam.chaser.PrimaryHandler.__get_reference_id_name__.lambda3
KeyError: 4
Process ChaserTask-9:
Traceback (most recent call last):
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.7.7-intel-mgiwa7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "parabam/chaser.pyx", line 701, in parabam.chaser.ChaserTask.run
  File "parabam/chaser.pyx", line 801, in __read_generator__
  File "parabam/chaser.pyx", line 820, in parabam.chaser.PrimaryHandler.__get_loner_type__
  File "parabam/chaser.pyx", line 813, in parabam.chaser.PrimaryHandler.__get_reference_id_name__
  File "parabam/chaser.pyx", line 810, in parabam.chaser.PrimaryHandler.__get_reference_id_name__.lambda3
KeyError: 6
Process ChaserTask-12:1:
Traceback (most recent call last):
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.7.7-intel-mgiwa7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "parabam/chaser.pyx", line 701, in parabam.chaser.ChaserTask.run
  File "parabam/chaser.pyx", line 801, in __read_generator__
  File "parabam/chaser.pyx", line 820, in parabam.chaser.PrimaryHandler.__get_loner_type__
  File "parabam/chaser.pyx", line 813, in parabam.chaser.PrimaryHandler.__get_reference_id_name__
  File "parabam/chaser.pyx", line 810, in parabam.chaser.PrimaryHandler.__get_reference_id_name__.lambda3
KeyError: 1
Process ChaserTask-12:2:
Traceback (most recent call last):
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.7.7-intel-mgiwa7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "parabam/chaser.pyx", line 701, in parabam.chaser.ChaserTask.run
  File "parabam/chaser.pyx", line 801, in __read_generator__
  File "parabam/chaser.pyx", line 820, in parabam.chaser.PrimaryHandler.__get_loner_type__
  File "parabam/chaser.pyx", line 813, in parabam.chaser.PrimaryHandler.__get_reference_id_name__
  File "parabam/chaser.pyx", line 810, in parabam.chaser.PrimaryHandler.__get_reference_id_name__.lambda3
KeyError: 9
Process ChaserTask-12:3:
Traceback (most recent call last):
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.7.7-intel-mgiwa7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "parabam/chaser.pyx", line 701, in parabam.chaser.ChaserTask.run
  File "parabam/chaser.pyx", line 801, in __read_generator__
  File "parabam/chaser.pyx", line 820, in parabam.chaser.PrimaryHandler.__get_loner_type__
  File "parabam/chaser.pyx", line 813, in parabam.chaser.PrimaryHandler.__get_reference_id_name__
  File "parabam/chaser.pyx", line 810, in parabam.chaser.PrimaryHandler.__get_reference_id_name__.lambda3
KeyError: 4
Process ChaserTask-12:4:
Traceback (most recent call last):
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.7.7-intel-mgiwa7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "parabam/chaser.pyx", line 701, in parabam.chaser.ChaserTask.run
  File "parabam/chaser.pyx", line 801, in __read_generator__
  File "parabam/chaser.pyx", line 820, in parabam.chaser.PrimaryHandler.__get_loner_type__
  File "parabam/chaser.pyx", line 813, in parabam.chaser.PrimaryHandler.__get_reference_id_name__
  File "parabam/chaser.pyx", line 810, in parabam.chaser.PrimaryHandler.__get_reference_id_name__.lambda3
KeyError: 9
Process ChaserTask-12:5:
Traceback (most recent call last):
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.7.7-intel-mgiwa7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "parabam/chaser.pyx", line 701, in parabam.chaser.ChaserTask.run
  File "parabam/chaser.pyx", line 801, in __read_generator__
  File "parabam/chaser.pyx", line 820, in parabam.chaser.PrimaryHandler.__get_loner_type__
  File "parabam/chaser.pyx", line 813, in parabam.chaser.PrimaryHandler.__get_reference_id_name__
  File "parabam/chaser.pyx", line 810, in parabam.chaser.PrimaryHandler.__get_reference_id_name__.lambda3
KeyError: 2
Process ChaserTask-12:6:
Traceback (most recent call last):
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.7.7-intel-mgiwa7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "parabam/chaser.pyx", line 701, in parabam.chaser.ChaserTask.run
  File "parabam/chaser.pyx", line 801, in __read_generator__
  File "parabam/chaser.pyx", line 820, in parabam.chaser.PrimaryHandler.__get_loner_type__
  File "parabam/chaser.pyx", line 813, in parabam.chaser.PrimaryHandler.__get_reference_id_name__
  File "parabam/chaser.pyx", line 810, in parabam.chaser.PrimaryHandler.__get_reference_id_name__.lambda3
KeyError: 15
Process ChaserTask-12:7:
Traceback (most recent call last):
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.7.7-intel-mgiwa7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "parabam/chaser.pyx", line 701, in parabam.chaser.ChaserTask.run
  File "parabam/chaser.pyx", line 801, in __read_generator__
  File "parabam/chaser.pyx", line 820, in parabam.chaser.PrimaryHandler.__get_loner_type__
  File "parabam/chaser.pyx", line 813, in parabam.chaser.PrimaryHandler.__get_reference_id_name__
  File "parabam/chaser.pyx", line 810, in parabam.chaser.PrimaryHandler.__get_reference_id_name__.lambda3
KeyError: 16
Process ChaserTask-12:8:
Traceback (most recent call last):
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.7.7-intel-mgiwa7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "parabam/chaser.pyx", line 701, in parabam.chaser.ChaserTask.run
  File "parabam/chaser.pyx", line 801, in __read_generator__
  File "parabam/chaser.pyx", line 820, in parabam.chaser.PrimaryHandler.__get_loner_type__
  File "parabam/chaser.pyx", line 813, in parabam.chaser.PrimaryHandler.__get_reference_id_name__
  File "parabam/chaser.pyx", line 810, in parabam.chaser.PrimaryHandler.__get_reference_id_name__.lambda3
KeyError: 12
Process ChaserTask-12:9:
Traceback (most recent call last):
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.7.7-intel-mgiwa7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "parabam/chaser.pyx", line 701, in parabam.chaser.ChaserTask.run
  File "parabam/chaser.pyx", line 801, in __read_generator__
  File "parabam/chaser.pyx", line 820, in parabam.chaser.PrimaryHandler.__get_loner_type__
  File "parabam/chaser.pyx", line 813, in parabam.chaser.PrimaryHandler.__get_reference_id_name__
  File "parabam/chaser.pyx", line 810, in parabam.chaser.PrimaryHandler.__get_reference_id_name__.lambda3
KeyError: 1
Process ChaserTask-12:10:
Traceback (most recent call last):
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.7.7-intel-mgiwa7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "parabam/chaser.pyx", line 701, in parabam.chaser.ChaserTask.run
  File "parabam/chaser.pyx", line 801, in __read_generator__
  File "parabam/chaser.pyx", line 820, in parabam.chaser.PrimaryHandler.__get_loner_type__
  File "parabam/chaser.pyx", line 813, in parabam.chaser.PrimaryHandler.__get_reference_id_name__
  File "parabam/chaser.pyx", line 810, in parabam.chaser.PrimaryHandler.__get_reference_id_name__.lambda3
KeyError: 0
```

Depending on the machine it was run on, the the error continues like this (multiple lines as folows):
`	- Read pairing in progress: 0.00% complete`
or like this:
```
- Reads processed: 45250000 Time: 15025
- Reads processed: 45250000 Time: 15107
- Reads processed: 45250000 Time: 15189
- Reads processed: 45250000 Time: 15272
- Reads processed: 45250000 Time: 15354
- Reads processed: 45250000 Time: 15437
- Reads processed: 45250000 Time: 15519
- Reads processed: 45250000 Time: 15602
```

Then the process was killed because the reserved time in PBS system run out. 

Could you advise what could be the problem please?

Thank you,
Kristina

**Comment by keiranmraine** [comment]
Likely solved by 4.0.0, please let me know if not,
